name: angular_quill
description: Angular dart component for the Quill rich text editor. Quill is a free, open source WYSIWYG editor built for the modern web.
version: 1.0.0
homepage: https://github.com/adamlofts/angular_quill

environment:
  sdk: '2.19.6'

dependencies:
  ngdart: ^8.0.0-dev.2
  ngforms: ^5.0.0-dev.1
  js: ^0.6.0

